In [66]:
# Прочитайте файл 2017_jun_final.csv за допомогою методу read_csv

import pandas as pd
import numpy as np

df = pd.read_csv("2017_jun_final.csv")
df

In [14]:
# Прочитайте отриману таблицю, використовуючи метод head

df.head()

,N,Должность,Язык.программирования,Специализация,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,...,Еще.студент,Уровень.английского,Предметная.область,Дата.заполнения,User.Agent,exp,current_job_exp,salary,Валюта,cls
0,1,Junior QA engineer,NaN,Manual QA,0.5,0.5,400,0,Харьков,до 10 человек,...,True,ниже среднего,"iOS,eCommerce",12/06/2017 12:38:08,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN,QA
1,2,Junior QA engineer,NaN,Manual QA,меньше 3 месяцев,меньше 3 месяцев,430,130,Харьков,свыше 1000 человек,...,True,выше среднего,Веб-разработка,12/06/2017 12:42:51,Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...,0.0,0.0,430,NaN,QA
2,3,Software Engineer,C#/.NET,NaN,4,1,2500,800,Киев,до 1000 человек,...,False,средний,"Веб-разработка,Корпоративные системы",12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500,NaN,DEV
3,4,Software Engineer,JavaScript,NaN,5,4,2000,400,Одесса,до 200 человек,...,False,ниже среднего,"Desktop Applications,Веб-разработка",12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000,NaN,DEV
4,5,Senior Software Engineer,JavaScript,NaN,10 и более лет,0.5,4500,500,Другой,до 10 человек,...,False,средний,"Desktop Applications,Веб-разработка",12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500,NaN,DEV

In [15]:
# Визначте розмір таблиці за допомогою методу shape

df.shape

(8704, 25)

In [16]:
# Визначте типи всіх стовпців за допомогою dataframe.dtypes

df.dtypes

N                                     int64
Должность                            object
Язык.программирования                object
Специализация                        object
Общий.опыт.работы                    object
Опыт.работы.на.текущем.месте         object
Зарплата.в.месяц                      int64
Изменение.зарплаты.за.12.месяцев      int64
Город                                object
Размер.компании                      object
Тип.компании                         object
Пол                                  object
Возраст                               int64
Образование                          object
Университет                          object
Еще.студент                            bool
Уровень.английского                  object
Предметная.область                   object
Дата.заполнения                      object
User.Agent                           object
exp                                 float64
current_job_exp                     float64
salary                                int64
Валюта                               object
cls                                  object
dtype: object

In [32]:
# Порахуйте, яка частка пропусків міститься в кожній колонці (використовуйте методи isnull та sum)

cnt = df.isnull().sum(axis=0)*100/8704
cnt.round(3)

N                                    0.000
Должность                            0.000
Язык.программирования               44.233
Специализация                       82.939
Общий.опыт.работы                    0.000
Опыт.работы.на.текущем.месте         0.000
Зарплата.в.месяц                     0.000
Изменение.зарплаты.за.12.месяцев     0.000
Город                                0.000
Размер.компании                      0.000
Тип.компании                         0.000
Пол                                  0.000
Возраст                              0.000
Образование                          0.000
Университет                          4.113
Еще.студент                          0.000
Уровень.английского                  0.000
Предметная.область                   2.562
Дата.заполнения                      0.000
User.Agent                           0.000
exp                                  0.000
current_job_exp                      0.000
salary                               0.000
Валюта                              99.885
cls                                 18.084
dtype: float64

In [43]:
# Видаліть усі стовпці з пропусками, крім стовпця Язык.программирования

df_tmp = df.isna().any()
col_not_del = ['Язык.программирования']
df_tmp[col_not_del] = False
df.drop(df_tmp.index[df_tmp], axis=1, inplace=True)

In [44]:
# Знову порахуйте, яка частка пропусків міститься в кожній колонці і переконайтеся, що залишився тільки стовпець 
# "Мова.програмування"

cnt = df.isnull().sum(axis=0)*100/8704
cnt.round(3)

N                                    0.000
Должность                            0.000
Язык.программирования               44.233
Общий.опыт.работы                    0.000
Опыт.работы.на.текущем.месте         0.000
Зарплата.в.месяц                     0.000
Изменение.зарплаты.за.12.месяцев     0.000
Город                                0.000
Размер.компании                      0.000
Тип.компании                         0.000
Пол                                  0.000
Возраст                              0.000
Образование                          0.000
Еще.студент                          0.000
Уровень.английского                  0.000
Дата.заполнения                      0.000
User.Agent                           0.000
exp                                  0.000
current_job_exp                      0.000
salary                               0.000
dtype: float64

In [50]:
# Видаліть усі рядки у вихідній таблиці за допомогою методу dropna

df = df.dropna()
df.head()

,N,Должность,Язык.программирования,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,Тип.компании,Пол,Возраст,Образование,Еще.студент,Уровень.английского,Дата.заполнения,User.Agent,exp,current_job_exp,salary
2,3,Software Engineer,C#/.NET,4,1,2500,800,Киев,до 1000 человек,Аутсорсинговая,мужской,26,Высшее,False,средний,12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500
3,4,Software Engineer,JavaScript,5,4,2000,400,Одесса,до 200 человек,Продуктовая,мужской,30,Среднее,False,ниже среднего,12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000
4,5,Senior Software Engineer,JavaScript,10 и более лет,0.5,4500,500,Другой,до 10 человек,Продуктовая,мужской,30,Техникум / Колледж,False,средний,12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500
6,7,Junior Software Engineer,C#/.NET,1,меньше 3 месяцев,600,100,Хмельницкий,до 50 человек,Аутсорсинговая,мужской,23,Высшее,False,ниже среднего,12/06/2017 13:04:26,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.0,0.0,600
7,8,Senior Software Engineer,C++,6,1,3300,500,Киев,до 10 человек,Продуктовая,мужской,28,Высшее,False,выше среднего,12/06/2017 13:04:27,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,6.0,1.0,3300

In [51]:
# Визначте новий розмір таблиці за допомогою методу shape
df.shape

(4854, 20)

In [64]:
# Використовуючи метод groupby, виконайте групування за стовпчиком "Посада"

df.groupby('Должность').head()

,N,Должность,Язык.программирования,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,Тип.компании,Пол,Возраст,Образование,Еще.студент,Уровень.английского,Дата.заполнения,User.Agent,exp,current_job_exp,salary
2,3,Software Engineer,C#/.NET,4,1,2500,800,Киев,до 1000 человек,Аутсорсинговая,мужской,26,Высшее,False,средний,12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500
3,4,Software Engineer,JavaScript,5,4,2000,400,Одесса,до 200 человек,Продуктовая,мужской,30,Среднее,False,ниже среднего,12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000
4,5,Senior Software Engineer,JavaScript,10 и более лет,0.5,4500,500,Другой,до 10 человек,Продуктовая,мужской,30,Техникум / Колледж,False,средний,12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500
6,7,Junior Software Engineer,C#/.NET,1,меньше 3 месяцев,600,100,Хмельницкий,до 50 человек,Аутсорсинговая,мужской,23,Высшее,False,ниже среднего,12/06/2017 13:04:26,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.0,0.0,600
7,8,Senior Software Engineer,C++,6,1,3300,500,Киев,до 10 человек,Продуктовая,мужской,28,Высшее,False,выше среднего,12/06/2017 13:04:27,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,6.0,1.0,3300
8,9,Junior Software Engineer,Java,0.5,0.5,550,550,Харьков,свыше 1000 человек,Аутсорсинговая,женский,23,Высшее,False,средний,12/06/2017 13:04:28,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,0.5,0.5,550
11,12,System Architect,Scala,10 и более лет,1,5600,1500,Киев,свыше 1000 человек,Аутстаффинговая,мужской,30,Высшее,False,выше среднего,12/06/2017 13:05:25,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,10.0,1.0,5600
12,13,Software Engineer,Python,1,меньше 3 месяцев,800,200,Киев,до 50 человек,Аутсорсинговая,мужской,26,Высшее,False,ниже среднего,12/06/2017 13:05:54,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,1.0,0.0,800
14,15,Software Engineer,Ruby/Rails,3,1,2500,500,Киев,до 50 человек,Продуктовая,мужской,27,Высшее,False,выше среднего,12/06/2017 13:06:32,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,3.0,1.0,2500
15,16,Senior Software Engineer,JavaScript,5,5,2900,300,Винница,до 200 человек,Аутсорсинговая,мужской,26,Высшее,False,продвинутый,12/06/2017 13:06:50,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...,5.0,5.0,2900
16,17,Software Engineer,JavaScript,4,1,2875,0,Киев,свыше 1000 человек,Аутсорсинговая,мужской,24,Высшее,False,продвинутый,12/06/2017 13:06:57,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,4.0,1.0,2875
17,18,Junior Software Engineer,C#/.NET,1,1,574,274,Киев,до 10 человек,Стартап,мужской,23,Высшее,False,продвинутый,12/06/2017 13:07:06,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.0,1.0,574
18,19,Senior Software Engineer,C++,4,0.5,3300,600,Киев,до 1000 человек,Аутсорсинговая,мужской,22,Высшее,True,выше среднего,12/06/2017 13:07:10,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4...,4.0,0.5,3300
24,25,Senior Software Engineer,Swift,6,1,2800,0,Киев,свыше 1000 человек,Аутсорсинговая,мужской,31,Высшее,False,выше среднего,12/06/2017 13:07:50,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) ...,6.0,1.0,2800
35,36,Junior Software Engineer,Java,1,1,350,350,Ужгород,до 50 человек,Аутсорсинговая,мужской,26,Высшее,False,выше среднего,12/06/2017 13:08:32,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,1.0,350
40,41,Junior Software Engineer,Swift,3,1.5,450,150,Другой,до 10 человек,Продуктовая,мужской,27,Высшее,False,ниже среднего,12/06/2017 13:09:06,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0...,3.0,1.5,450
44,45,Technical Lead,Perl,6,4,3400,250,Киев,свыше 1000 человек,Аутстаффинговая,мужской,36,Незаконченное высшее,False,выше среднего,12/06/2017 13:09:29,Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X...,6.0,4.0,3400
52,53,Technical Lead,C++,10 и более лет,4,4500,0,Киев,свыше 1000 человек,Аутсорсинговая,мужской,35,Высшее,False,продвинутый,12/06/2017 13:09:57,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,10.0,4.0,4500
54,55,Technical Lead,PHP,6,3,3000,500,Киев,до 10 человек,Аутстаффинговая,мужской,24,Высшее,False,выше среднего,12/06/2017 13:10:01,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,6.0,3.0,3000
111,112,Technical Lead,C,10 и более лет,10 и более лет,4150,150,Днепр,до 200 человек,Аутстаффинговая,мужской,33,Высшее,False,выше среднего,12/06/2017 13:14:33,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,10.0,10.0,4150
219,220,Technical Lead,SQL,10 и более лет,4,3000,100,Киев,до 200 человек,Продуктовая,мужской,36,Высшее,False,ниже среднего,12/06/2017 13:32:39,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,10.0,4.0,3000
480,481,System Architect,Java,10 и более лет,7,4300,300,Харьков,до 50 человек,Аутсорсинговая,мужской,28,Высшее,False,выше среднего,12/06/2017 14:20:01,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...,10.0,7.0,4300
730,731,System Architect,C#/.NET,10 и более лет,5,4000,200,Харьков,свыше 1000 человек,Аутсорсинговая,мужской,37,Высшее,False,выше среднего,12/06/2017 15:14:56,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,10.0,5.0,4000
733,734,System Architect,C++,10 и более лет,2,4500,0,Львов,до 1000 человек,Аутсорсинговая,мужской,32,Кандидат,False,продвинутый,12/06/2017 15:15:32,Mozilla/5.0 (Windows NT 6.3; Win64; x64) Apple...,10.0,2.0,4500
1135,1136,System Architect,C#/.NET,6,5,3600,600,Киев,до 50 человек,Другая,мужской,29,Высшее,False,выше среднего,12/06/2017 17:24:15,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,6.0,5.0,3600
1706,1707,Data Scientist / Data Analyst,Java,1.5,меньше 3 месяцев,2700,300,Львов,до 50 человек,Стартап,мужской,35,Высшее,False,выше среднего,12/06/2017 22:47:41,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.5,0.0,2700
2049,2050,HTML coder,JavaScript,1,0.5,400,200,Львов,до 50 человек,Аутсорсинговая,мужской,24,Высшее,False,ниже среднего,13/06/2017 09:31:53,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.0,0.5,400
2911,2912,DevOps,Golang,8,меньше 3 месяцев,7000,5500,Киев,до 200 человек,Аутсорсинговая,мужской,29,Незаконченное высшее,False,средний,13/06/2017 13:29:21,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,8.0,0.0,7000
2936,2937,HTML coder,JavaScript,1,0.5,400,100,Ровно,до 200 человек,Аутсорсинговая,мужской,36,Высшее,False,средний,13/06/2017 13:37:55,Mozilla/5.0 (Linux; Android 5.0.2; Lenovo A601...,1.0,0.5,400
3097,3098,HTML coder,JavaScript,2,1,600,350,Одесса,до 10 человек,Продуктовая,мужской,25,Высшее,False,ниже среднего,13/06/2017 14:30:48,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,2.0,1.0,600
4098,4099,Product Manager,Delphi,7,7,3000,500,Киев,до 50 человек,Продуктовая,мужской,35,Высшее,False,ниже среднего,14/06/2017 17:23:27,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,7.0,7.0,3000
4315,4316,HTML coder,JavaScript,0.5,0.5,385,0,Киев,до 10 человек,Аутсорсинговая,мужской,21,Незаконченное высшее,False,средний,15/06/2017 10:59:43,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,385
5105,5106,Team lead,PHP,7,4,4000,500,Киев,до 10 человек,Продуктовая,мужской,29,Высшее,False,выше среднего,20/06/2017 11:03:25,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,7.0,4.0,4000
6304,6305,HTML coder,PHP,4,меньше 3 месяцев,500,-300,Киев,до 10 человек,Продуктовая,мужской,30,Высшее,False,ниже среднего,21/06/2017 21:36:43,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,0.0,500
6712,6713,ERP / CRM,PHP,2,1,2000,1000,Черкассы,до 10 человек,Другая,мужской,29,Незаконченное высшее,True,средний,25/06/2017 14:21:44,Mozilla/5.0 (Windows NT 6.3; Win64; x64) Apple...,2.0,1.0,2000
7004,7005,Team lead,C#/.NET,5,5,2500,500,Харьков,до 1000 человек,Аутсорсинговая,мужской,25,Высшее,False,выше среднего,26/06/2017 16:07:25,Mozilla/5.0 (Windows NT 6.3; Win64; x64) Apple...,5.0,5.0,2500

In [102]:
# Створіть новий DataFrame, де для згрупованих даних за стовпчиком "Посада", 
# виконайте агрегацію даних за допомогою методу agg і знайдіть мінімальне та максимальне значення у 
# стовпчику "Зарплата.в.місяць"

df_new = df
df_new = df.groupby(['Должность'])['Зарплата.в.месяц'].agg([np.min, np.max])
df_new

                               amin   amax
Должность
Data Scientist / Data Analyst  2700   2700
DevOps                         7000   7000
ERP / CRM                      2000   2000
HTML coder                      385    600
Junior Software Engineer         75   2600
Product Manager                3000   3000
Senior Software Engineer        350   9200
Software Engineer               100   7000
System Architect                400  10000
Team lead                      2500   4000
Technical Lead                  500  18000

In [103]:
# Створіть функцію fill_avg_salary, яка повертатиме середнє значення заробітної плати на місяць. 
# Використовуйте її для методу apply та створіть новий стовпчик "avg"


def fill_avg_salary(salary):
    return salary.mean()

df_new['avg'] = df_new.apply(fill_avg_salary, axis=1)
df_new

                               amin   amax     avg
Должность
Data Scientist / Data Analyst  2700   2700  2700.0
DevOps                         7000   7000  7000.0
ERP / CRM                      2000   2000  2000.0
HTML coder                      385    600   492.5
Junior Software Engineer         75   2600  1337.5
Product Manager                3000   3000  3000.0
Senior Software Engineer        350   9200  4775.0
Software Engineer               100   7000  3550.0
System Architect                400  10000  5200.0
Team lead                      2500   4000  3250.0
Technical Lead                  500  18000  9250.0

In [105]:
# Створіть описову статистику за допомогою методу describe для нового стовпчика.

df_new['avg'].describe()

count      11.000000
mean     3868.636364
std      2554.599128
min       492.500000
25%      2350.000000
50%      3250.000000
75%      4987.500000
max      9250.000000
Name: avg, dtype: float64

In [106]:
# Збережіть отриману таблицю в CSV файл

df_new.to_csv('2017_jun_final_new.csv', encoding='utf8')